# -*- coding: utf-8 -*-

SCAN_STATUS_COMPLETED = "completed"
SCAN_STATUS_RUNNING = "running"
SCAN_STATUS_ERROR = "error"
SCAN_STATUS_CHOICES = [SCAN_STATUS_COMPLETED, SCAN_STATUS_RUNNING, SCAN_STATUS_ERROR]

OUTPUT_FORMAT_YAML = "yaml"
OUTPUT_FORMAT_TABLE = "table"
OUTPUT_FORMAT_CHOICES = [OUTPUT_FORMAT_YAML, OUTPUT_FORMAT_TABLE]
